// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NoorPath.Pricing.Infrastructure;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace NoorPath.Pricing.Infrastructure.Migrations
{
    [DbContext(typeof(PricingDbContext))]
    [Migration("20260731001001_VS04PublishedPriceVersions")]
    partial class VS04PublishedPriceVersions
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("pricing")
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("NoorPath.Pricing.Infrastructure.OccupancyPriceRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("Occupancy")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<Guid>("PricePlanId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("PricePlanId", "Occupancy")
                        .IsUnique();

                    b.ToTable("occupancy_prices", "pricing");
                });

            modelBuilder.Entity("NoorPath.Pricing.Infrastructure.PricePlanRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.Property<Guid>("DepartureId")
                        .HasColumnType("uuid");

                    b.Property<string>("OperatorId")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("DepartureId")
                        .IsUnique();

                    b.HasIndex("OperatorId");

                    b.ToTable("price_plans", "pricing");
                });

            modelBuilder.Entity("NoorPath.Pricing.Infrastructure.PricingAuditRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("ActorAccountId")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("CorrelationId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("DepartureId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PricePlanId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Version")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PricePlanId");

                    b.HasIndex("DepartureId", "Version");

                    b.ToTable("pricing_audits", "pricing");
                });

            modelBuilder.Entity("NoorPath.Pricing.Infrastructure.PriceVersionRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.Property<Guid>("DepartureId")
                        .HasColumnType("uuid");

                    b.Property<string>("OperatorId")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<Guid>("PricePlanId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("PublishedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PublishedByAccountId")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<int>("SourcePlanVersion")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("DepartureId")
                        .IsUnique();

                    b.HasIndex("PricePlanId", "SourcePlanVersion")
                        .IsUnique();

                    b.ToTable("price_versions", "pricing");
                });

            modelBuilder.Entity("NoorPath.Pricing.Infrastructure.PublishedOccupancyPriceRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("Occupancy")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<Guid>("PriceVersionId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("PriceVersionId", "Occupancy")
                        .IsUnique();

                    b.ToTable("published_occupancy_prices", "pricing");
                });

            modelBuilder.Entity("NoorPath.Pricing.Infrastructure.OccupancyPriceRecord", b =>
                {
                    b.HasOne("NoorPath.Pricing.Infrastructure.PricePlanRecord", null)
                        .WithMany()
                        .HasForeignKey("PricePlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("NoorPath.Pricing.Infrastructure.PricingAuditRecord", b =>
                {
                    b.HasOne("NoorPath.Pricing.Infrastructure.PricePlanRecord", null)
                        .WithMany()
                        .HasForeignKey("PricePlanId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("NoorPath.Pricing.Infrastructure.PriceVersionRecord", b =>
                {
                    b.HasOne("NoorPath.Pricing.Infrastructure.PricePlanRecord", null)
                        .WithMany()
                        .HasForeignKey("PricePlanId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("NoorPath.Pricing.Infrastructure.PublishedOccupancyPriceRecord", b =>
                {
                    b.HasOne("NoorPath.Pricing.Infrastructure.PriceVersionRecord", null)
                        .WithMany()
                        .HasForeignKey("PriceVersionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
