// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NoorPath.Inventory.Infrastructure;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace NoorPath.Inventory.Infrastructure.Migrations
{
    [DbContext(typeof(InventoryDbContext))]
    partial class InventoryDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("inventory")
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("NoorPath.Inventory.Infrastructure.InventoryAuditRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("ActorAccountId")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("CorrelationId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("DepartureId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("InventoryConfigurationId")
                        .HasColumnType("uuid");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(240)
                        .HasColumnType("character varying(240)");

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Version")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("InventoryConfigurationId");

                    b.HasIndex("DepartureId", "Version");

                    b.ToTable("inventory_audits", "inventory");
                });

            modelBuilder.Entity("NoorPath.Inventory.Infrastructure.InventoryCommitmentRecord", b =>
                {
                    b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uuid");
                    b.Property<string>("AccountId").IsRequired().HasMaxLength(120).HasColumnType("character varying(120)");
                    b.Property<Guid>("BookingId").HasColumnType("uuid");
                    b.Property<string>("CorrelationId").IsRequired().HasMaxLength(100).HasColumnType("character varying(100)");
                    b.Property<DateTimeOffset>("CreatedAtUtc").HasColumnType("timestamp with time zone");
                    b.Property<Guid>("HoldId").HasColumnType("uuid");
                    b.Property<Guid>("InventoryPoolId").HasColumnType("uuid");
                    b.Property<Guid>("PaymentAttemptId").HasColumnType("uuid");
                    b.Property<int>("Quantity").HasColumnType("integer");
                    b.HasKey("Id");
                    b.HasIndex("BookingId").IsUnique();
                    b.HasIndex("HoldId").IsUnique();
                    b.HasIndex("InventoryPoolId", "CreatedAtUtc");
                    b.ToTable("inventory_commitments", "inventory", t => t.HasCheckConstraint("CK_inventory_commitments_Quantity_Positive", "\"Quantity\" > 0"));
                });

            modelBuilder.Entity("NoorPath.Inventory.Infrastructure.InventoryConfigurationRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("DepartureId")
                        .HasColumnType("uuid");

                    b.Property<string>("OperatorId")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("DepartureId")
                        .IsUnique();

                    b.HasIndex("OperatorId");

                    b.ToTable("inventory_configurations", "inventory");
                });

            modelBuilder.Entity("NoorPath.Inventory.Infrastructure.InventoryCommitmentRecord", b =>
                {
                    b.HasOne("NoorPath.Inventory.Infrastructure.InventoryHoldRecord", null).WithMany().HasForeignKey("HoldId").OnDelete(DeleteBehavior.Restrict).IsRequired();
                    b.HasOne("NoorPath.Inventory.Infrastructure.InventoryPoolRecord", null).WithMany().HasForeignKey("InventoryPoolId").OnDelete(DeleteBehavior.Restrict).IsRequired();
                });

            modelBuilder.Entity("NoorPath.Inventory.Infrastructure.InventoryHoldRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AccountId")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("CorrelationId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("DepartureId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("ExpiresAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("IdempotencyKeyHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<Guid>("InventoryPoolId")
                        .HasColumnType("uuid");

                    b.Property<string>("Occupancy")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("OperatorId")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<Guid>("QuoteId")
                        .HasColumnType("uuid");

                    b.Property<string>("RequestFingerprint")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<DateTimeOffset?>("TerminalAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("AccountId", "DepartureId", "Occupancy")
                        .IsUnique()
                        .HasFilter("\"State\" = 'Active'");

                    b.HasIndex("AccountId", "DepartureId", "Occupancy", "State");

                    b.HasIndex("AccountId", "IdempotencyKeyHash")
                        .IsUnique();

                    b.HasIndex("InventoryPoolId", "State", "ExpiresAtUtc");

                    b.HasIndex("QuoteId")
                        .IsUnique()
                        .HasFilter("\"State\" = 'Active'");

                    b.HasIndex("QuoteId", "State");

                    b.ToTable("inventory_holds", "inventory", t =>
                        {
                            t.HasCheckConstraint("CK_inventory_holds_Expiry_After_Creation", "\"ExpiresAtUtc\" > \"CreatedAtUtc\"");

                            t.HasCheckConstraint("CK_inventory_holds_Quantity_Positive", "\"Quantity\" > 0");

                            t.HasCheckConstraint("CK_inventory_holds_State", "\"State\" IN ('Active', 'Released', 'Expired')");
                        });
                });

            modelBuilder.Entity("NoorPath.Inventory.Infrastructure.InventoryPoolRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Capacity")
                        .HasColumnType("integer");

                    b.Property<Guid>("InventoryConfigurationId")
                        .HasColumnType("uuid");

                    b.Property<string>("Occupancy")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.HasKey("Id");

                    b.HasIndex("InventoryConfigurationId", "Occupancy")
                        .IsUnique();

                    b.ToTable("inventory_pools", "inventory");
                });

            modelBuilder.Entity("NoorPath.Inventory.Infrastructure.InventoryAuditRecord", b =>
                {
                    b.HasOne("NoorPath.Inventory.Infrastructure.InventoryConfigurationRecord", null)
                        .WithMany()
                        .HasForeignKey("InventoryConfigurationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("NoorPath.Inventory.Infrastructure.InventoryHoldRecord", b =>
                {
                    b.HasOne("NoorPath.Inventory.Infrastructure.InventoryPoolRecord", null)
                        .WithMany()
                        .HasForeignKey("InventoryPoolId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("NoorPath.Inventory.Infrastructure.InventoryPoolRecord", b =>
                {
                    b.HasOne("NoorPath.Inventory.Infrastructure.InventoryConfigurationRecord", null)
                        .WithMany()
                        .HasForeignKey("InventoryConfigurationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
