using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable
namespace NoorPath.Catalogue.Infrastructure.Migrations;

[DbContext(typeof(CatalogueDbContext))]
[Migration("202607280001_InitialCatalogue")]
public partial class InitialCatalogue : Migration
{
    protected override void Up(MigrationBuilder migrationBuilder)
    {
        migrationBuilder.EnsureSchema(name: "catalogue");
        migrationBuilder.CreateTable(name: "packages", schema: "catalogue", columns: table => new { Id = table.Column<Guid>(type: "uuid", nullable: false), OperatorId = table.Column<string>(type: "character varying(80)", maxLength: 80, nullable: false), OperatorName = table.Column<string>(type: "character varying(120)", maxLength: 120, nullable: false), Name = table.Column<string>(type: "character varying(120)", maxLength: 120, nullable: false), Summary = table.Column<string>(type: "character varying(300)", maxLength: 300, nullable: false), Tier = table.Column<string>(type: "character varying(40)", maxLength: 40, nullable: false) }, constraints: table => table.PrimaryKey("PK_packages", x => x.Id));
        migrationBuilder.CreateTable(name: "batches", schema: "catalogue", columns: table => new { Id = table.Column<Guid>(type: "uuid", nullable: false), PackageId = table.Column<Guid>(type: "uuid", nullable: false), DepartureCity = table.Column<string>(type: "character varying(80)", maxLength: 80, nullable: false), Route = table.Column<string>(type: "character varying(160)", maxLength: 160, nullable: false), DepartureDate = table.Column<DateOnly>(type: "date", nullable: false), ReturnDate = table.Column<DateOnly>(type: "date", nullable: false), Capacity = table.Column<int>(type: "integer", nullable: false), Availability = table.Column<int>(type: "integer", nullable: false), Status = table.Column<int>(type: "integer", nullable: false), Version = table.Column<int>(type: "integer", nullable: false), PublishedAt = table.Column<DateTimeOffset>(type: "timestamp with time zone", nullable: true) }, constraints: table => { table.PrimaryKey("PK_batches", x => x.Id); table.ForeignKey("FK_batches_packages_PackageId", x => x.PackageId, "catalogue", "packages", "Id", onDelete: ReferentialAction.Restrict); });
        migrationBuilder.CreateTable(name: "inclusions", schema: "catalogue", columns: table => new { Id = table.Column<Guid>(type: "uuid", nullable: false), PackageId = table.Column<Guid>(type: "uuid", nullable: false), Position = table.Column<int>(type: "integer", nullable: false), Text = table.Column<string>(type: "character varying(80)", maxLength: 80, nullable: false) }, constraints: table => { table.PrimaryKey("PK_inclusions", x => x.Id); table.ForeignKey("FK_inclusions_packages_PackageId", x => x.PackageId, "catalogue", "packages", "Id", onDelete: ReferentialAction.Cascade); });
        migrationBuilder.CreateTable(name: "price_versions", schema: "catalogue", columns: table => new { Id = table.Column<Guid>(type: "uuid", nullable: false), BatchId = table.Column<Guid>(type: "uuid", nullable: false), Currency = table.Column<string>(type: "character varying(3)", maxLength: 3, nullable: false), TotalStartingPrice = table.Column<decimal>(type: "numeric(12,2)", precision: 12, scale: 2, nullable: false), EffectiveAt = table.Column<DateTimeOffset>(type: "timestamp with time zone", nullable: false), Version = table.Column<int>(type: "integer", nullable: false) }, constraints: table => { table.PrimaryKey("PK_price_versions", x => x.Id); table.ForeignKey("FK_price_versions_batches_BatchId", x => x.BatchId, "catalogue", "batches", "Id", onDelete: ReferentialAction.Cascade); });
        migrationBuilder.CreateTable(name: "publication_audits", schema: "catalogue", columns: table => new { Id = table.Column<Guid>(type: "uuid", nullable: false), BatchId = table.Column<Guid>(type: "uuid", nullable: false), Actor = table.Column<string>(type: "character varying(100)", maxLength: 100, nullable: false), CorrelationId = table.Column<string>(type: "character varying(100)", maxLength: 100, nullable: false), PreviousStatus = table.Column<string>(type: "character varying(20)", maxLength: 20, nullable: false), NewStatus = table.Column<string>(type: "character varying(20)", maxLength: 20, nullable: false), ExpectedVersion = table.Column<int>(type: "integer", nullable: false), Timestamp = table.Column<DateTimeOffset>(type: "timestamp with time zone", nullable: false) }, constraints: table => { table.PrimaryKey("PK_publication_audits", x => x.Id); table.ForeignKey("FK_publication_audits_batches_BatchId", x => x.BatchId, "catalogue", "batches", "Id", onDelete: ReferentialAction.Restrict); });
        migrationBuilder.CreateIndex("IX_batches_PackageId", "batches", "PackageId", "catalogue"); migrationBuilder.CreateIndex("IX_inclusions_PackageId_Position", "inclusions", new[] { "PackageId", "Position" }, "catalogue", unique: true); migrationBuilder.CreateIndex("IX_price_versions_BatchId", "price_versions", "BatchId", "catalogue"); migrationBuilder.CreateIndex("IX_publication_audits_BatchId", "publication_audits", "BatchId", "catalogue", unique: true);
    }
    protected override void Down(MigrationBuilder migrationBuilder) { migrationBuilder.DropTable("inclusions", "catalogue"); migrationBuilder.DropTable("price_versions", "catalogue"); migrationBuilder.DropTable("publication_audits", "catalogue"); migrationBuilder.DropTable("batches", "catalogue"); migrationBuilder.DropTable("packages", "catalogue"); }
}
