// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NoorPath.Booking.Infrastructure;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace NoorPath.Booking.Infrastructure.Migrations
{
    [DbContext(typeof(BookingDbContext))]
    [Migration("20260809120806_VS33DepartureGroupLeader")]
    partial class VS33DepartureGroupLeader
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("booking")
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("NoorPath.Booking.Infrastructure.AccommodationAssignmentAuditRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("ActorAccountId")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<Guid>("BookingId")
                        .HasColumnType("uuid");

                    b.Property<string>("CorrelationId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTimeOffset>("OccurredAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("OperatorId")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<Guid?>("PreviousRoomId")
                        .HasColumnType("uuid");

                    b.Property<int>("PreviousRoomVersion")
                        .HasColumnType("integer");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("ResultingRoomVersion")
                        .HasColumnType("integer");

                    b.Property<Guid?>("RoomId")
                        .HasColumnType("uuid");

                    b.Property<string>("Stay")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<Guid?>("TravellerId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("BookingId", "OccurredAtUtc");

                    b.HasIndex("RoomId", "OccurredAtUtc");

                    b.ToTable("accommodation_assignment_audits", "booking");
                });

            modelBuilder.Entity("NoorPath.Booking.Infrastructure.AccommodationAssignmentRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("AssignedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("BookingId")
                        .HasColumnType("uuid");

                    b.Property<string>("OperatorId")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<Guid>("RoomId")
                        .HasColumnType("uuid");

                    b.Property<string>("Stay")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<Guid>("TravellerId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RoomId", "TravellerId")
                        .IsUnique();

                    b.HasIndex("BookingId", "Stay", "TravellerId")
                        .IsUnique();

                    b.ToTable("accommodation_assignments", "booking");
                });

            modelBuilder.Entity("NoorPath.Booking.Infrastructure.AccommodationRoomRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BookingId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsLocked")
                        .HasColumnType("boolean");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("OperatorId")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("RoomType")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("Stay")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("BookingId", "Stay", "Label")
                        .IsUnique();

                    b.HasIndex("OperatorId", "BookingId", "Stay");

                    b.ToTable("accommodation_rooms", "booking", t =>
                        {
                            t.HasCheckConstraint("CK_accommodation_rooms_Version_Positive", "\"Version\" > 0");
                        });
                });

            modelBuilder.Entity("NoorPath.Booking.Infrastructure.BookingAmendmentRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ActorAccountId")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("AfterSnapshotJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("BeforeSnapshotJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<Guid>("BookingId")
                        .HasColumnType("uuid");

                    b.Property<string>("CorrelationId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.Property<DateTimeOffset>("OccurredAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("OperatorId")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("PreviewFingerprint")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<int>("PreviousBookingVersion")
                        .HasColumnType("integer");

                    b.Property<decimal>("PriceDelta")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("ResultingBookingVersion")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("BookingId", "OccurredAtUtc");

                    b.HasIndex("BookingId", "ResultingBookingVersion")
                        .IsUnique();

                    b.ToTable("booking_amendments", "booking", t =>
                        {
                            t.HasCheckConstraint("CK_booking_amendments_Version_Progression", "\"ResultingBookingVersion\" = \"PreviousBookingVersion\" + 1");
                        });
                });

            modelBuilder.Entity("NoorPath.Booking.Infrastructure.BookingCancellationAuditRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AccountId")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("ActorAccountId")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<Guid>("BookingId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CancellationRequestId")
                        .HasColumnType("uuid");

                    b.Property<string>("CorrelationId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("DetailJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<DateTimeOffset>("OccurredAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Reason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("Id");

                    b.HasIndex("BookingId", "OccurredAtUtc");

                    b.HasIndex("CancellationRequestId", "OccurredAtUtc");

                    b.ToTable("cancellation_audits", "booking");
                });

            modelBuilder.Entity("NoorPath.Booking.Infrastructure.BookingCancellationRequestRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AccountId")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<DateTimeOffset?>("AppliedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("BookingId")
                        .HasColumnType("uuid");

                    b.Property<string>("CalculationJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.Property<int>("DaysBeforeDeparture")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("DecidedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DecisionActorAccountId")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("DecisionReason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTimeOffset>("DepartureAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FailureCode")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<int>("FeeBasisPoints")
                        .HasColumnType("integer");

                    b.Property<string>("IdempotencyKeyHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<decimal>("NonRefundableAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("OperatorId")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<decimal>("PercentageFee")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("PolicyTimeZoneId")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("PolicyVersion")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("ReasonCategory")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<int>("RefundProcessingBusinessDays")
                        .HasColumnType("integer");

                    b.Property<decimal>("RefundableAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("RequestFingerprint")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset>("RequestedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("SettledAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer");

                    b.Property<int>("WindowMinimumDaysBeforeDeparture")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("BookingId")
                        .IsUnique()
                        .HasFilter("\"State\" IN ('Requested', 'Approved', 'Applying', 'Exception')");

                    b.HasIndex("AccountId", "IdempotencyKeyHash")
                        .IsUnique();

                    b.HasIndex("AccountId", "BookingId", "RequestedAtUtc");

                    b.HasIndex("OperatorId", "State", "UpdatedAtUtc");

                    b.ToTable("cancellation_requests", "booking", t =>
                        {
                            t.HasCheckConstraint("CK_cancellation_requests_Amount_Composition", "\"SettledAmount\" = \"PercentageFee\" + \"NonRefundableAmount\" + \"RefundableAmount\"");

                            t.HasCheckConstraint("CK_cancellation_requests_Amounts_NonNegative", "\"SettledAmount\" >= 0 AND \"PercentageFee\" >= 0 AND \"NonRefundableAmount\" >= 0 AND \"RefundableAmount\" >= 0");

                            t.HasCheckConstraint("CK_cancellation_requests_FeeBasisPoints", "\"FeeBasisPoints\" >= 0 AND \"FeeBasisPoints\" <= 10000");

                            t.HasCheckConstraint("CK_cancellation_requests_RefundDays", "\"RefundProcessingBusinessDays\" > 0");
                        });
                });

            modelBuilder.Entity("NoorPath.Booking.Infrastructure.BookingInstalmentRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<Guid>("BookingId")
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("DueDate")
                        .HasColumnType("date");

                    b.Property<int>("Sequence")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("BookingId", "Sequence")
                        .IsUnique();

                    b.ToTable("booking_instalments", "booking", t =>
                        {
                            t.HasCheckConstraint("CK_booking_instalments_Amount_Positive", "\"Amount\" > 0");
                        });
                });

            modelBuilder.Entity("NoorPath.Booking.Infrastructure.BookingOutboxRecord", b =>
                {
                    b.Property<Guid>("EventId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AggregateId")
                        .HasColumnType("uuid");

                    b.Property<string>("AggregateType")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<int>("AggregateVersion")
                        .HasColumnType("integer");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("integer");

                    b.Property<string>("CausationId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("CorrelationId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<int>("EventVersion")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("NextAttemptAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("OccurredAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<DateTimeOffset?>("ProcessedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("EventId");

                    b.HasIndex("State", "NextAttemptAtUtc");

                    b.ToTable("outbox_messages", "booking");
                });

            modelBuilder.Entity("NoorPath.Booking.Infrastructure.BookingRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AccountId")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<Guid?>("CancellationRequestId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("CancelledAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ConfirmationExceptionCode")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<DateTimeOffset?>("ConfirmedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CorrelationId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.Property<Guid>("DepartureId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("DueNow")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("IdempotencyKeyHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<Guid?>("InventoryCommitmentId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("InventoryHoldId")
                        .HasColumnType("uuid");

                    b.Property<string>("Occupancy")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("OperatorId")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<Guid>("PriceVersionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("QuoteId")
                        .HasColumnType("uuid");

                    b.Property<string>("Reference")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)");

                    b.Property<decimal>("Remaining")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("RequestFingerprint")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<Guid?>("SettledPaymentAttemptId")
                        .HasColumnType("uuid");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)");

                    b.Property<decimal>("Total")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<int>("TravellerCount")
                        .HasColumnType("integer");

                    b.Property<decimal>("UnitPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CancellationRequestId")
                        .IsUnique();

                    b.HasIndex("InventoryHoldId")
                        .IsUnique();

                    b.HasIndex("QuoteId")
                        .IsUnique();

                    b.HasIndex("Reference")
                        .IsUnique();

                    b.HasIndex("AccountId", "CreatedAtUtc");

                    b.HasIndex("AccountId", "IdempotencyKeyHash")
                        .IsUnique();

                    b.HasIndex("State", "UpdatedAtUtc");

                    b.ToTable("bookings", "booking", t =>
                        {
                            t.HasCheckConstraint("CK_bookings_Amounts_NonNegative", "\"UnitPrice\" >= 0 AND \"Total\" >= 0 AND \"DueNow\" >= 0 AND \"Remaining\" >= 0");

                            t.HasCheckConstraint("CK_bookings_Total_Composition", "\"Total\" = \"DueNow\" + \"Remaining\"");

                            t.HasCheckConstraint("CK_bookings_TravellerCount_Positive", "\"TravellerCount\" > 0");

                            t.HasCheckConstraint("CK_bookings_Version_Positive", "\"Version\" > 0");
                        });
                });

            modelBuilder.Entity("NoorPath.Booking.Infrastructure.BookingTravellerRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BookingId")
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<int>("Position")
                        .HasColumnType("integer");

                    b.Property<Guid>("TravellerId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("BookingId", "Position")
                        .IsUnique();

                    b.HasIndex("BookingId", "TravellerId")
                        .IsUnique();

                    b.ToTable("booking_travellers", "booking");
                });

            modelBuilder.Entity("NoorPath.Booking.Infrastructure.DepartureHandoverAuditRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("ActorAccountId")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<int>("BlockedCount")
                        .HasColumnType("integer");

                    b.Property<string>("CorrelationId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("DepartureId")
                        .HasColumnType("uuid");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTimeOffset>("OccurredAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("OperatorId")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<int>("PreviousVersion")
                        .HasColumnType("integer");

                    b.Property<int>("ResultingVersion")
                        .HasColumnType("integer");

                    b.Property<int>("TravellerCount")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("OperatorId", "DepartureId", "OccurredAtUtc");

                    b.ToTable("departure_handover_audits", "booking");
                });

            modelBuilder.Entity("NoorPath.Booking.Infrastructure.DepartureHandoverRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("CompletedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CompletedByAccountId")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("DepartureId")
                        .HasColumnType("uuid");

                    b.Property<string>("FinalNote")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("GroupLeaderName")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("boolean");

                    b.Property<string>("OperatorId")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("OperatorId", "DepartureId")
                        .IsUnique();

                    b.ToTable("departure_handovers", "booking", t =>
                        {
                            t.HasCheckConstraint("CK_departure_handovers_Version_Positive", "\"Version\" > 0");
                        });
                });

            modelBuilder.Entity("NoorPath.Booking.Infrastructure.DepartureManifestAuditRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("ActorAccountId")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<Guid>("BookingId")
                        .HasColumnType("uuid");

                    b.Property<string>("CorrelationId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("DepartureId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("OccurredAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("OperatorId")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<bool>("PreviousIsAcknowledged")
                        .HasColumnType("boolean");

                    b.Property<string>("PreviousNote")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("PreviousVersion")
                        .HasColumnType("integer");

                    b.Property<bool>("ResultingIsAcknowledged")
                        .HasColumnType("boolean");

                    b.Property<string>("ResultingNote")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("ResultingVersion")
                        .HasColumnType("integer");

                    b.Property<Guid>("TravellerId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TravellerId", "OccurredAtUtc");

                    b.HasIndex("OperatorId", "DepartureId", "OccurredAtUtc");

                    b.ToTable("departure_manifest_audits", "booking");
                });

            modelBuilder.Entity("NoorPath.Booking.Infrastructure.DepartureManifestTravellerRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ActorAccountId")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<Guid>("BookingId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("DepartureId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsAcknowledged")
                        .HasColumnType("boolean");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("OperatorId")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<Guid>("TravellerId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("DepartureId", "UpdatedAtUtc");

                    b.HasIndex("OperatorId", "DepartureId", "TravellerId")
                        .IsUnique();

                    b.ToTable("departure_manifest_travellers", "booking", t =>
                        {
                            t.HasCheckConstraint("CK_departure_manifest_travellers_Version_Positive", "\"Version\" > 0");
                        });
                });

            modelBuilder.Entity("NoorPath.Booking.Infrastructure.AccommodationAssignmentAuditRecord", b =>
                {
                    b.HasOne("NoorPath.Booking.Infrastructure.BookingRecord", null)
                        .WithMany()
                        .HasForeignKey("BookingId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("NoorPath.Booking.Infrastructure.AccommodationAssignmentRecord", b =>
                {
                    b.HasOne("NoorPath.Booking.Infrastructure.BookingRecord", null)
                        .WithMany()
                        .HasForeignKey("BookingId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("NoorPath.Booking.Infrastructure.AccommodationRoomRecord", null)
                        .WithMany()
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("NoorPath.Booking.Infrastructure.AccommodationRoomRecord", b =>
                {
                    b.HasOne("NoorPath.Booking.Infrastructure.BookingRecord", null)
                        .WithMany()
                        .HasForeignKey("BookingId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("NoorPath.Booking.Infrastructure.BookingAmendmentRecord", b =>
                {
                    b.HasOne("NoorPath.Booking.Infrastructure.BookingRecord", null)
                        .WithMany()
                        .HasForeignKey("BookingId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("NoorPath.Booking.Infrastructure.BookingCancellationAuditRecord", b =>
                {
                    b.HasOne("NoorPath.Booking.Infrastructure.BookingCancellationRequestRecord", null)
                        .WithMany()
                        .HasForeignKey("CancellationRequestId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("NoorPath.Booking.Infrastructure.BookingCancellationRequestRecord", b =>
                {
                    b.HasOne("NoorPath.Booking.Infrastructure.BookingRecord", null)
                        .WithMany()
                        .HasForeignKey("BookingId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("NoorPath.Booking.Infrastructure.BookingInstalmentRecord", b =>
                {
                    b.HasOne("NoorPath.Booking.Infrastructure.BookingRecord", null)
                        .WithMany()
                        .HasForeignKey("BookingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("NoorPath.Booking.Infrastructure.BookingTravellerRecord", b =>
                {
                    b.HasOne("NoorPath.Booking.Infrastructure.BookingRecord", null)
                        .WithMany()
                        .HasForeignKey("BookingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
