using Microsoft.EntityFrameworkCore;
using NoorPath.Booking;
using NoorPath.Booking.Infrastructure;
using NoorPath.Catalogue.Infrastructure;
using NoorPath.Documents;
using NoorPath.Documents.Infrastructure;
using NoorPath.Operators;

public static class DocumentEndpoints
{
    public static void MapDocuments(this WebApplication app)
    {
        var customer = app.MapGroup("/api/v1/bookings/{bookingId:guid}/documents").RequireAuthorization();
        customer.MapGet("", CustomerRequirements);
        customer.MapPost("/{requirementId:guid}/uploads", StartUpload);
        customer.MapPost("/submissions/{submissionId:guid}/complete", CompleteUpload);
        customer.MapGet("/submissions/{submissionId:guid}/access", CustomerAccess);
        var review = app.MapGroup("/api/v1/operator/documents").RequireAuthorization();
        review.MapGet("", ReviewQueue);
        review.MapGet("/{submissionId:guid}/access", OperatorAccess);
        review.MapPost("/{submissionId:guid}/review", Review);
    }

    private static async Task<(BookingRecord?, string?)> CustomerBooking(Guid id,HttpContext http,BookingDbContext db,CancellationToken ct)
    { var p=http.User.GetCurrentPrincipal(); if(p is null)return(null,null); return(await db.Bookings.SingleOrDefaultAsync(x=>x.Id==id&&x.AccountId==p.AccountId.Value&&x.State==BookingState.Confirmed,ct),p.AccountId.Value); }
    private static async Task<IResult> CustomerRequirements(Guid bookingId,HttpContext http,BookingDbContext bookingDb,DocumentsDbContext db,TimeProvider clock,CancellationToken ct)
    {
        var (booking,_)=await CustomerBooking(bookingId,http,bookingDb,ct); if(booking is null)return Results.NotFound();
        var travellers=await bookingDb.Travellers.Where(x=>x.BookingId==bookingId).OrderBy(x=>x.Position).ToArrayAsync(ct);
        if(!await db.Requirements.AnyAsync(x=>x.BookingId==bookingId,ct)) { foreach(var t in travellers) foreach(var kind in DocumentPolicy.RequiredKinds) db.Requirements.Add(new(){Id=Guid.NewGuid(),BookingId=bookingId,TravellerId=t.TravellerId,Kind=kind,PolicyVersion=DocumentPolicy.Version,CreatedAtUtc=clock.GetUtcNow()}); await db.SaveChangesAsync(ct); }
        var reqs=await db.Requirements.Where(x=>x.BookingId==bookingId).ToArrayAsync(ct); var ids=reqs.Select(x=>x.Id).ToArray(); var submissions=await db.Submissions.Where(x=>ids.Contains(x.RequirementId)).OrderByDescending(x=>x.CreatedAtUtc).ToArrayAsync(ct);
        return Results.Ok(new { policyVersion=DocumentPolicy.Version, ready=reqs.All(r=>submissions.FirstOrDefault(s=>s.RequirementId==r.Id)?.State==SubmissionState.Approved), travellers=travellers.Select(t=>new { t.TravellerId,t.FullName,requirements=reqs.Where(r=>r.TravellerId==t.TravellerId).Select(r=>new { r.Id,kind=r.Kind.ToString(),submission=submissions.FirstOrDefault(s=>s.RequirementId==r.Id) is {} s?new { s.Id,state=s.State.ToString(),malwareStatus=s.MalwareStatus.ToString(),s.ReviewReason,s.Version}:null }) }) });
    }
    public sealed record UploadRequest(string ContentType,long Size);
    private static async Task<IResult> StartUpload(Guid bookingId,Guid requirementId,UploadRequest request,HttpContext http,BookingDbContext bookingDb,CatalogueDbContext catalogue,DocumentsDbContext db,IPrivateDocumentStorage storage,TimeProvider clock,CancellationToken ct)
    {
        var (booking,actor)=await CustomerBooking(bookingId,http,bookingDb,ct); if(booking is null)return Results.NotFound(); if(!DocumentPolicy.AllowedTypes.Contains(request.ContentType)||request.Size<=0||request.Size>DocumentPolicy.MaximumBytes)return Results.BadRequest(new{code="invalid_file",message="Choose a PDF, JPEG or PNG up to 10 MB."});
        var requirement=await db.Requirements.SingleOrDefaultAsync(x=>x.Id==requirementId&&x.BookingId==bookingId,ct); if(requirement is null)return Results.NotFound(); var previous=await db.Submissions.Where(x=>x.RequirementId==requirementId&&!new[]{SubmissionState.Superseded,SubmissionState.Deleted}.Contains(x.State)).ToArrayAsync(ct); foreach(var old in previous)old.State=SubmissionState.Superseded;
        var returnDate=await catalogue.DepartureBatches.Where(x=>x.Id==booking.DepartureId).Select(x=>(DateOnly?)x.ReturnDate).SingleOrDefaultAsync(ct); var key=storage.CreateOpaqueKey(); var item=new DocumentSubmissionRecord{Id=Guid.NewGuid(),RequirementId=requirementId,ObjectKey=key,DeclaredContentType=request.ContentType,DeclaredSize=request.Size,State=SubmissionState.Quarantined,MalwareStatus=MalwareStatus.Pending,CreatedAtUtc=clock.GetUtcNow(),DeleteAfterUtc=returnDate?.ToDateTime(TimeOnly.MinValue,DateTimeKind.Utc).AddDays(30)}; db.Submissions.Add(item); db.Audit.Add(Audit(item.Id,"upload_authorized",actor!,"customer upload",clock)); await db.SaveChangesAsync(ct); var expires=clock.GetUtcNow()+DocumentPolicy.SignedUrlLifetime; return Results.Ok(new{submissionId=item.Id,uploadUrl=storage.PresignUpload(key,request.ContentType,request.Size,expires),expiresAtUtc=expires});
    }
    private static async Task<IResult> CompleteUpload(Guid bookingId,Guid submissionId,HttpContext http,BookingDbContext bookingDb,DocumentsDbContext db,IPrivateDocumentStorage storage,IMalwareScanner scanner,TimeProvider clock,CancellationToken ct)
    {
        var (booking,actor)=await CustomerBooking(bookingId,http,bookingDb,ct); if(booking is null)return Results.NotFound(); var item=await OwnedSubmission(bookingId,submissionId,db,ct); if(item is null)return Results.NotFound(); if(item.State!=SubmissionState.Quarantined)return Results.Conflict(new{code="stale_submission"}); var info=await storage.GetInfoAsync(item.ObjectKey,ct); if(info is null||info.Size!=item.DeclaredSize||info.Size>DocumentPolicy.MaximumBytes||!string.Equals(info.ContentType,item.DeclaredContentType,StringComparison.OrdinalIgnoreCase)){ item.MalwareStatus=MalwareStatus.Indeterminate; await db.SaveChangesAsync(ct); return Results.UnprocessableEntity(new{code="validation_failed",message="The file could not be validated. Please upload it again."}); }
        await using var objectStream=await storage.OpenReadAsync(item.ObjectKey,ct); await using var stream=new MemoryStream((int)info.Size); await objectStream.CopyToAsync(stream,ct); var header=stream.GetBuffer().AsSpan(0,(int)Math.Min(8,stream.Length)); if(!DocumentPolicy.SignatureMatches(item.DeclaredContentType,header)){item.MalwareStatus=MalwareStatus.Indeterminate;await db.SaveChangesAsync(ct);return Results.UnprocessableEntity(new{code="signature_mismatch"});} stream.Position=0;
        item.MalwareStatus=await scanner.ScanAsync(stream,ct); if(item.MalwareStatus==MalwareStatus.Safe)item.State=SubmissionState.UnderReview; db.Audit.Add(Audit(item.Id,"validation_completed",actor!,item.MalwareStatus.ToString(),clock)); await db.SaveChangesAsync(ct); return item.MalwareStatus==MalwareStatus.Safe?Results.Ok(new{state=item.State.ToString()}):Results.UnprocessableEntity(new{code="quarantined",message="The file remains unavailable while safety checks are incomplete."});
    }
    private static async Task<DocumentSubmissionRecord?> OwnedSubmission(Guid bookingId,Guid submissionId,DocumentsDbContext db,CancellationToken ct)=>await (from s in db.Submissions join r in db.Requirements on s.RequirementId equals r.Id where s.Id==submissionId&&r.BookingId==bookingId select s).SingleOrDefaultAsync(ct);
    private static async Task<IResult> CustomerAccess(Guid bookingId,Guid submissionId,HttpContext http,BookingDbContext bookingDb,DocumentsDbContext db,IPrivateDocumentStorage storage,TimeProvider clock,CancellationToken ct){var(b,a)=await CustomerBooking(bookingId,http,bookingDb,ct);if(b is null)return Results.NotFound();var s=await OwnedSubmission(bookingId,submissionId,db,ct);if(s is null||s.MalwareStatus!=MalwareStatus.Safe)return Results.NotFound();return await Signed(s,a!,"customer access",db,storage,clock,ct);}
    private static async Task<OperatorAccess?> Reviewer(HttpContext http,IOperatorAccess access,CancellationToken ct){var p=http.User.GetCurrentPrincipal();return p is null?null:await access.FindActiveMembershipAsync(p.AccountId,ct);}
    private static async Task<IResult> ReviewQueue(HttpContext http,IOperatorAccess access,BookingDbContext bookings,DocumentsDbContext db,CancellationToken ct){var op=await Reviewer(http,access,ct);if(op is null||!op.IsAllowed(OperatorPermissions.DocumentReview))return Results.Forbid();var bookingIds=await bookings.Bookings.Where(x=>x.OperatorId==op.OperatorId&&x.State==BookingState.Confirmed).Select(x=>x.Id).ToArrayAsync(ct);var items=await(from s in db.Submissions join r in db.Requirements on s.RequirementId equals r.Id where bookingIds.Contains(r.BookingId)&&s.State==SubmissionState.UnderReview&&s.MalwareStatus==MalwareStatus.Safe select new{s.Id,r.BookingId,r.TravellerId,kind=r.Kind.ToString(),s.CreatedAtUtc,s.Version}).ToArrayAsync(ct);return Results.Ok(new{items});}
    private static async Task<(DocumentSubmissionRecord?,OperatorAccess?)> OperatorSubmission(Guid id,HttpContext http,IOperatorAccess access,BookingDbContext bookings,DocumentsDbContext db,CancellationToken ct){var op=await Reviewer(http,access,ct);if(op is null||!op.IsAllowed(OperatorPermissions.DocumentReview))return(null,op);var bookingIds=bookings.Bookings.Where(x=>x.OperatorId==op.OperatorId).Select(x=>x.Id);return(await(from s in db.Submissions join r in db.Requirements on s.RequirementId equals r.Id where s.Id==id&&bookingIds.Contains(r.BookingId) select s).SingleOrDefaultAsync(ct),op);}
    private static async Task<IResult> OperatorAccess(Guid submissionId,HttpContext http,IOperatorAccess access,BookingDbContext bookings,DocumentsDbContext db,IPrivateDocumentStorage storage,TimeProvider clock,CancellationToken ct){var(s,op)=await OperatorSubmission(submissionId,http,access,bookings,db,ct);if(op is null||!op.IsAllowed(OperatorPermissions.DocumentReview))return Results.Forbid();if(s is null||s.State!=SubmissionState.UnderReview||s.MalwareStatus!=MalwareStatus.Safe)return Results.NotFound();return await Signed(s,http.User.GetCurrentPrincipal()!.AccountId.Value,"document review",db,storage,clock,ct);}
    public sealed record ReviewRequest(ReviewDecision Decision,string? Reason,int Version);
    private static async Task<IResult> Review(Guid submissionId,ReviewRequest request,HttpContext http,IOperatorAccess access,BookingDbContext bookings,DocumentsDbContext db,TimeProvider clock,CancellationToken ct){var(s,op)=await OperatorSubmission(submissionId,http,access,bookings,db,ct);if(op is null||!op.IsAllowed(OperatorPermissions.DocumentReview))return Results.Forbid();if(s is null)return Results.NotFound();if(s.Version!=request.Version)return Results.Conflict(new{code="stale_review"});if(request.Decision!=ReviewDecision.Approve&&string.IsNullOrWhiteSpace(request.Reason))return Results.BadRequest(new{code="reason_required"});try{s.State=DocumentPolicy.Review(s.State,s.MalwareStatus,request.Decision);}catch(InvalidOperationException){return Results.Conflict(new{code="invalid_transition"});}s.ReviewReason=request.Reason?.Trim();s.ReviewedBy=http.User.GetCurrentPrincipal()!.AccountId.Value;s.ReviewedAtUtc=clock.GetUtcNow();s.Version++;db.Audit.Add(Audit(s.Id,"review_"+request.Decision,s.ReviewedBy,s.ReviewReason??"approved",clock));await db.SaveChangesAsync(ct);return Results.Ok(new{state=s.State.ToString(),s.Version});}
    private static async Task<IResult> Signed(DocumentSubmissionRecord s,string actor,string purpose,DocumentsDbContext db,IPrivateDocumentStorage storage,TimeProvider clock,CancellationToken ct){db.Audit.Add(Audit(s.Id,"content_access",actor,purpose,clock));await db.SaveChangesAsync(ct);var expires=clock.GetUtcNow()+DocumentPolicy.SignedUrlLifetime;return Results.Ok(new{accessUrl=storage.PresignAccess(s.ObjectKey,expires),expiresAtUtc=expires});}
    private static DocumentAuditRecord Audit(Guid id,string action,string actor,string purpose,TimeProvider clock)=>new(){Id=Guid.NewGuid(),SubmissionId=id,Action=action,ActorId=actor,Purpose=purpose,OccurredAtUtc=clock.GetUtcNow()};
}
